private
tips

	^ {
		'arrows' -> 'navigation shortkeys'.
		'<ctrl + arrows>' -> 'navigation on search bar'.
		'<ctrl + arrow down>' -> 'makes a full search' .
		'<meta+b>'  -> 'filters for Classes' .
		'<meta+m>' -> 'filters for Implementors' .
		'<meta+p>' -> 'filters for Packages' .
		'you can resize the window' -> 'the size will be saved' .
		'settings icon' -> 'history, size and insertSelection' .
		'<shift + enter>' -> 'opens Pulse on Environment' .
		'<shift + meta + enter>' -> 'opens Pulse on Commands' .
		'<shift + alt + enter>' -> 'opens Pulse on Windows' .
		'<shift + enter> while on Pulse' -> 'opens Finder' 
	}