accessing
maxCandidatesAdded
"Maximum amount of candidates added from events before of full update. This is done so when looking for
something that has a small amount of results, it gives you the results it finds before looking in the whole system. 
For eg. StObjectTranscriptPresenter --> 2 results
Without this, this search doesn't give you those 2 results before it looks in the whole system."
	^ 3