private
tips

	^ {
		'arrows' -> 'navigation shortkeys'.
		'ctrl + arrows' -> 'navigation on search bar'.
		'<meta+b>'  -> 'filters for Classes' .
		'<meta+m>' -> 'filters for Implementors' .
		'<meta+p>' -> 'filters for Packages' .
		'<shift + enter>' -> 'opens Pulse on Environment' .
		'<shift + meta + enter>' -> 'opens Pulse on Commands' .
		'<shift + alt + enter>' -> 'opens Pulse on Windows' .
		'<shift + enter> while on Pulse' -> 'opens Finder'
	}